CREATE TABLE IF NOT EXISTS triggerdata (
run_number integer NOT NULL,
version integer NOT NULL,
tname text NOT NULL,
event_no integer NOT NULL,
seconds integer NOT NULL,
nanoseconds integer NOT NULL,
wr_name text NOT NULL,
wr_event_no integer NOT NULL,
wr_seconds integer NOT NULL,
wr_nanoseconds integer NOT NULL,
enable_type integer NOT NULL,
enable_seconds integer NOT NULL,
enable_nanoseconds integer NOT NULL,
gate_id integer NOT NULL,
gate_type integer NOT NULL,
gate_id_bnb integer NOT NULL,
gate_id_numi integer NOT NULL,
gate_id_bnboff integer NOT NULL,
gate_id_numioff integer NOT NULL,
beam_seconds integer NOT NULL,
beam_nanoseconds integer NOT NULL,
trigger_type integer NOT NULL,
trigger_source integer NOT NULL,
cryo1_e_conn_0 text NOT NULL,
cryo1_e_conn_2 text NOT NULL,
cryo2_w_conn_0 text NOT NULL,
cryo2_w_conn_2 text NOT NULL,
cryo1_east_counts integer NOT NULL,
cryo2_west_counts integer NOT NULL,
mj_adder_source_east integer NOT NULL DEFAULT -1,
mj_adder_source_west integer NOT NULL DEFAULT -1
);
